# Generated by Django 5.2.5 on 2025-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("confirmed", "Confirmed"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("departure_time", models.DateTimeField()),
                ("seats", models.PositiveIntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=6)),
                ("car_make", models.CharField(blank=True, max_length=50)),
                ("car_model", models.CharField(blank=True, max_length=50)),
                ("car_color", models.CharField(blank=True, max_length=30)),
                ("plate", models.CharField(blank=True, max_length=20)),
                ("pickup_notes", models.TextField(blank=True)),
                ("dropoff_notes", models.TextField(blank=True)),
            ],
        ),
    ]
